-- ============================================================================
-- T1 — Core tables
-- ----------------------------------------------------------------------------
-- account_id is denormalized onto every domain table on purpose:
--   1. the worker bypasses RLS (service_role) and MUST filter account_id
--      explicitly (spec §2) — having it local avoids deep joins;
--   2. RLS policies stay flat/fast (single membership check, no joins).
-- ============================================================================

-- accounts: the operator/tenant. v1 is single-operator, multi-tenant ready.
create table public.accounts (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- account_users: membership mapping auth.users -> accounts. Backbone of RLS.
create table public.account_users (
  account_id  uuid not null references public.accounts(id) on delete cascade,
  user_id     uuid not null references auth.users(id) on delete cascade,
  role        text not null default 'owner' check (role in ('owner', 'member')),
  created_at  timestamptz not null default now(),
  primary key (account_id, user_id)
);
create index account_users_user_id_idx on public.account_users (user_id);

-- products: catalog candidates and approved products.
create table public.products (
  id                 uuid primary key default gen_random_uuid(),
  account_id         uuid not null references public.accounts(id) on delete cascade,
  external_ref       text,
  affiliate_platform public.affiliate_platform not null default 'tiktok_shop',
  title              text not null,
  price_brl          numeric(12,2) not null check (price_brl >= 0),
  commission_pct     numeric(5,2) not null default 0 check (commission_pct >= 0 and commission_pct <= 100),
  category           text,
  affiliate_link     text,
  score              numeric,
  score_breakdown    jsonb not null default '{}'::jsonb,
  status             public.pipeline_status not null default 'product_candidate',
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  -- dedupe catalog imports per platform. external_ref NULL => manual entry,
  -- and Postgres treats NULLs as distinct so manual rows never collide.
  unique (account_id, affiliate_platform, external_ref),
  -- composite key so child tables can FK on (id, account_id) and thereby
  -- guarantee child.account_id always equals the parent's account_id.
  unique (id, account_id)
);
create index products_account_status_idx on public.products (account_id, status);
create index products_account_score_idx on public.products (account_id, score desc nulls last);

-- scripts: N angle variations generated by Claude per approved product (§7).
create table public.scripts (
  id             uuid primary key default gen_random_uuid(),
  product_id     uuid not null,
  account_id     uuid not null references public.accounts(id) on delete cascade,
  angle          text not null,
  hook           text not null,
  body           text not null,
  cta            text not null,
  variant_index  integer not null default 0 check (variant_index >= 0),
  status         public.pipeline_status not null default 'script_generating',
  model_used     text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (product_id, variant_index),
  unique (id, account_id),
  -- composite FK enforces script.account_id == product.account_id
  foreign key (product_id, account_id) references public.products (id, account_id) on delete cascade
);
create index scripts_account_status_idx on public.scripts (account_id, status);
create index scripts_product_idx on public.scripts (product_id);

-- videos: HeyGen generation jobs and results. Costs are first-class citizens
-- (cost_usd_estimated is NOT NULL) per spec §3.
create table public.videos (
  id                  uuid primary key default gen_random_uuid(),
  script_id           uuid not null,
  product_id          uuid not null,
  account_id          uuid not null references public.accounts(id) on delete cascade,
  heygen_job_id       text,
  avatar_tier         public.avatar_tier not null default 'iii',
  duration_seconds    numeric(10,2) check (duration_seconds >= 0),
  cost_usd_estimated  numeric(10,4) not null default 0 check (cost_usd_estimated >= 0),
  cost_usd_actual     numeric(10,4) check (cost_usd_actual >= 0),
  video_url           text,
  status              public.pipeline_status not null default 'video_generating',
  error               text,
  retry_count         integer not null default 0 check (retry_count >= 0),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (id, account_id),
  -- composite FKs enforce video.account_id == script.account_id == product.account_id
  foreign key (script_id, account_id)  references public.scripts (id, account_id)  on delete cascade,
  foreign key (product_id, account_id) references public.products (id, account_id) on delete cascade
);
-- idempotency: one row per HeyGen job; re-submission cannot duplicate the job.
create unique index videos_heygen_job_id_key on public.videos (heygen_job_id) where heygen_job_id is not null;
create index videos_account_status_idx on public.videos (account_id, status);
create index videos_script_idx on public.videos (script_id);

-- compliance_checks: the mandatory gate before publication (§9). One per video.
create table public.compliance_checks (
  id                 uuid primary key default gen_random_uuid(),
  video_id           uuid not null unique,
  account_id         uuid not null references public.accounts(id) on delete cascade,
  ai_label_required  boolean not null default true,
  claims_ok          boolean,
  notes              text,
  reviewed_by        uuid references auth.users(id) on delete set null,
  reviewed_at        timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  -- composite FK enforces compliance_check.account_id == video.account_id
  foreign key (video_id, account_id) references public.videos (id, account_id) on delete cascade
);
create index compliance_checks_account_idx on public.compliance_checks (account_id);

-- publications: manual publication record (§6 publication screen).
create table public.publications (
  id                   uuid primary key default gen_random_uuid(),
  video_id             uuid not null,
  account_id           uuid not null references public.accounts(id) on delete cascade,
  tiktok_post_url      text,
  published_at         timestamptz,
  affiliate_link_used  text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (id, account_id),
  -- composite FK enforces publication.account_id == video.account_id
  foreign key (video_id, account_id) references public.videos (id, account_id) on delete cascade
);
create index publications_account_idx on public.publications (account_id);
create index publications_video_idx on public.publications (video_id);

-- performance: per-publication metrics. v1 manual/import; structure ready for
-- automated collection later (§13).
create table public.performance (
  id              uuid primary key default gen_random_uuid(),
  publication_id  uuid not null,
  account_id      uuid not null references public.accounts(id) on delete cascade,
  views           bigint not null default 0 check (views >= 0),
  clicks          bigint not null default 0 check (clicks >= 0),
  orders          bigint not null default 0 check (orders >= 0),
  gmv_brl         numeric(14,2) not null default 0 check (gmv_brl >= 0),
  commission_brl  numeric(14,2) not null default 0 check (commission_brl >= 0),
  collected_at    timestamptz not null default now(),
  created_at      timestamptz not null default now(),
  -- composite FK enforces performance.account_id == publication.account_id
  foreign key (publication_id, account_id) references public.publications (id, account_id) on delete cascade
);
create index performance_account_idx on public.performance (account_id);
create index performance_publication_idx on public.performance (publication_id);

-- pipeline_events: append-only audit log of every state transition (§3, §4).
-- Written automatically by triggers (next migration). Users may only read.
create table public.pipeline_events (
  id             uuid primary key default gen_random_uuid(),
  account_id     uuid not null references public.accounts(id) on delete cascade,
  entity_type    text not null,
  entity_id      uuid not null,
  from_status    public.pipeline_status,
  to_status      public.pipeline_status,
  actor          public.pipeline_actor not null default 'system',
  actor_user_id  uuid references auth.users(id) on delete set null,
  payload        jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now()
);
create index pipeline_events_entity_idx on public.pipeline_events (entity_type, entity_id);
create index pipeline_events_account_idx on public.pipeline_events (account_id, created_at desc);
